spring:
  application:
    name: market-collector-lotte
  main:
    web-application-type: none
  profiles:
    active: ${TECHX_ENV:default}
  devtools:
    restart:
      exclude: resources/db/**
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
#      uri: mongodb://tradexmts:techxcompany123@172.31.245.221:27017/tradex-market
      uri: mongodb://admin:traM8qzM8RwXrCfL@172.33.30.22:27017/tradex-market
    redis:
      host: 172.33.30.22
      port: 6379
      password:
logging:
  file:
    name: /logs/application.log
  level:
    root: WARN
    org.springframework: WARN
    com.difisoft.htsconnection.socket.nonblocking: INFO
    com.difisoft: INFO
    in: WARN
    out: WARN

app:
  domain: "${TRADEX_ENV_DOMAIN:tradex}"
  clusterId: ${spring.application.name}
  serviceName: market-collector-lotte
  nodeId: "${TRADEX_ENV_NODE_ID}${TRADEX_ENV_INSTANCE_ID:0}"
  serverHourOffset: 7
  disableInitDb: false
  initDbTopic: "extraUpdate"
  receivePacketTimeout: 90000
  receivePacketTimeoutScheduler: 30000
  mediaType: "03"
  enableQuery: false
  kafkaUrl: 172.33.30.21:9092
  enableInitMarket: true
  apiConnection:
#    baseUrl: http://172.33.30.23:8100/
    baseUrl: https://tnhsvpro.nhsv.vn/lotte/
    indexListApi: tsol/apikey/tuxsvc/market/indexs-list
    queryStockListByIndex: tsol/apikey/tuxsvc/market/symbols
    stockQuotes: tsol/apikey/tuxsvc/market/stock-quote
    indexQuotes: tsol/apikey/tuxsvc/market/market-quote
    etfQuotes: tsol/apikey/tuxsvc/market/etf-quote
    cwQuotes: tsol/apikey/tuxsvc/market/cw-quote
    stockDaily: tsol/apikey/tuxsvc/market/stock-daily
    indexDaily: tsol/apikey/tuxsvc/market/index-daily
    symbolNames: tsol/apikey/tuxsvc/market/securities-name
    symbolPrices: tsol/apikey/tuxsvc/market/securities-price
    bestBidAsks: tsol/apikey/tuxsvc/market/best-bid-offer
#    apiKey: qJxAtDmMuDEan9kUWsY4UuMugFvrYeMe
    apiKey: qJxAtDmMuDEan9kUWsY4UuMugFvrYeMe
  accountDownload:
    system: nhsv
    username: "${HTS_USER}"
    password: "${HTS_PASSWORD}"
    notSendOtp: true
    mediaType: "04"
  marketConf:
    symbolStaticBucket: market
    indexName:
      hnx: "HNX"
      upcom: "UPCOM"
      vn: "VN"
    fileConfig:
      defaultType: MINIO
      minio:
#        region: ap-southeast-1
#        baseUrl: http://172.33.30.21:8000
        baseUrl: https://file.nhsv-dev.tradex.vn
        accessKey: "J3nq1XTWxFQzv6Js51OY"
        privateKey: "bnGZo6an7bgiF0lTB83xmrVfujYEAVnYwAFpiPTU"
        buckets:
          - name: market
  topics:
    market: market
    realtimeService: realtime
    configuration: configuration
    user: user
    marketInit: marketInit
    userUtility: user-utility
    notification: notification
    refreshData: refreshData
    symbolInfoUpdate: symbolInfoUpdate
    requestResponseListener: ${spring.application.name}.{uuid}
    quoteRecover: quoteRecover
    requestListener: ${app.clusterId}

  realtime:
    useDefaultPort: false
    connectionDelay: 1000
    count: false
    maxRetry: 1
    minHour: 8
    maxHour: 16
    numberCodesToRegister: 1
    startLogin: false
    subscribeFilter:
      IndexAutoItem:
        includes:
          exchanges:
            - "09"
            - "19"
            - "39"
    workingTime:
      from: "01:44"
      to: "18:05"
      weekdays: # see https://docs.oracle.com/javase/7/docs/api/constant-values.html#java.util.Calendar.SUNDAY
        - 2 # Monday
        - 3
        - 4
        - 5
        - 6
    websocketConnections: []
    websocketConnections2:
      - name: INDEX-WS
        url: ws://172.33.30.36:9900
        codeType: INDEX
        channels: []
#          - sub/pro.pub.auto.idxqt./<code> # index quote
        codeMapping:
          VNINDEX: VN
      - name: SESSION-WS
        url: ws://172.33.30.36:9900
        codeType: MARKET-STATUS
        channels:
          - sub/pro.pub.auto.tickerNews.*/ # session status
      - name: STOCK-HOSE
        url: ws://172.33.30.36:9900
        codeType: STOCK
        exchange: HOSE
        channels:
          - sub/pro.pub.auto.qt./ # quote
          - sub/pro.pub.auto.bo./ # bid-ask
      - name: STOCK-HNX
        url: ws://172.33.30.36:9900
        codeType: STOCK
        exchange: HNX
        channels:
          - sub/pro.pub.auto.qt./ # quote
          - sub/pro.pub.auto.bo./ # bid-ask
      - name: STOCK-UPCOM
        url: ws://172.33.30.36:9900
        codeType: STOCK
        exchange: UPCOM
        channels:
          - sub/pro.pub.auto.qt./ # quote
          - sub/pro.pub.auto.bo./ # bid-ask
      - name: CW
        url: ws://172.33.30.36:9900
        codeType: CW
        channels:
          - sub/pro.pub.auto.qt./ # quote
          - sub/pro.pub.auto.bo./ # bid-ask
      - name: ETF
        url: ws://172.33.30.36:9900
        codeType: ETF
        channels:
          - sub/pro.pub.auto.qt./ # quote
          - sub/pro.pub.auto.bo./ # bid-ask
    accounts: []
#      - username: "difihts01"
#        password: "nhsv2023"
#        notSendOtp: true
#        system: nhsv
#        mediaType: \${app.mediaType}
#        name: "Realtime-Index"
#        codeType: INDEX
#        noOfThread: 1
#        ip: "118.70.73.122"
#        topics:
#          - IndexAutoItem
    topics:
      StockAutoItem:
        topic: quoteUpdate
        uri: Update
        transformTo: StockUpdateData
      IndexAutoItem:
        topic: quoteUpdate
        uri: Update
        transformTo: IndexUpdateData
      BidOfferAutoItem:
        topic: bidOfferUpdate
        uri: Update
        transformTo: BidOfferData
      DealNoticeAutoItem:
        topic: dealNoticeUpdate
        uri: Update
        transformTo: DealNoticeData
      AdvertisedAutoItem:
        topic: advertisedUpdate
        uri: advertisedUpdate
        transformTo: AdvertisedData
      FuturesAutoItem:
        topic: quoteUpdate
        uri: Update
        transformTo: FuturesUpdateData
      FuturesBidOfferItem:
        topic: bidOfferUpdate
        uri: Update
        transformTo: FuturesBidOfferData
      A78AutoItem:
        topic: marketStatus
        uri: Update
        transformTo: MarketStatusData
      TickMesgItem:
        topic: tickerMesgUpdate
        uri: Update
        transformTo: TickerMesgData
      CWAutoItem:
        topic: quoteUpdate
        uri: Update
        transformTo: StockUpdateData
      CWBidOfferAutoItem:
        topic: bidOfferUpdate
        uri: Update
        transformTo: BidOfferData
  websocketConf:
    host: 172.33.30.23
    port: 9900
    ssl: false
  sysConf:
    vcsc:
      host: vpro.vcsc.com.vn
      loginPort: 8000
      dataPort: 21001
      marketPort: 22003
      secCode: "068"
    vcsc1:
      host: vpro.vcsc.com.vn
      loginPort: 8000
      dataPort: 21001
      marketPort: 22003
      secCode: "068"
    vcsc2:
      host: vpro.vcsc.com.vn
      loginPort: 8000
      dataPort: 21001
      marketPort: 22001
      secCode: "068"
    nhsv:
      host: nhhts.nhsv.vn
      loginPort: 8000
      dataPort: 21001
      marketPort: 22001
      secCode: "039"
  statusMap:
    "[(HOSE) Start of Preopen period for entire market]": "ATO"
    "[(HOSE) Market Open]": "LO"
    "[(HOSE) Finish Intermission Period]": "LO"
    "[(HOSE) Begin Intermission Period]": "INTERMISSION"
    "[(HOSE) Start of Recap stream, Start of Call Market]": "ATC"
    "[(HOSE) Market Close, Begin Runoff Period]": "RUNOFF"
    "[(HOSE) End Runoff Period]": "CLOSED"
    "[(HNX) ATO]": "ATO"
    "[(HNX) Continous session]": "LO"
    "[(HNX) Pause]": "INTERMISSION"
    "[(HNX) At time close session]": "ATC"
    "[(HNX) PLO session]": "PLO"
    "[(HNX) Agreement trading session]": "PLO"
    "[(HNX) Close market]": "CLOSED"
    "[(HNX) Finished receive order of current day]": "CLOSED"
    "[(UPCOM) Continous session]": "LO"
    "[(UPCOM) Pause]": "INTERMISSION"
    "[(UPCOM) Close market]": "CLOSED"
    "[(UPCOM) Finished receive order of current day]": "CLOSED"
  highlightMap:
    VN: 1
    VN30: 2
    HNX: 3
    HNX30: 4
    UPCOM: 5
    VNALLShare: 6
    VNXALLShare: 7
    VN100: 8
  logRealtimePacket: false
  schedulers:
    resetCacheMapLastTradingVolume: "0 0 0,1,11,12,13,14,15,16 * * MON-FRI"
    resetCacheMapSequence: "0 0 0,1,11,12,13,14,15,16 * * MON-FRI"
    startRealtime1st: "0 00 2 * * MON-FRI"
    stopRealtime1st: "0 35 4 * * MON-FRI"
    startRealtime2nd: "0 58 5 * * MON-FRI"
    stopRealtime2nd: "0 05 8 * * MON-FRI"
    downloadSymbol: "0 0,15,30,55 1 * * MON-FRI"
    saveMonitorData: "0 0 5,9 * * *"
    resetMonitorData: "0 0 17 * * *"
    riseFallStockRankSave: "0 */1 1-18 * * *"
    rightInfoSave: "0 40 */1 * * *"
  timeStartReceiveBidAsk: "01:40"
  timeStopReceiveBidAsk: "24:00"
  holidayUrl: ${TRADEX_ENV_HOLIDAY_URL|https://paave-mobile-resource-uat.s3.ap-southeast-1.amazonaws.com/holidays.json}
  holidayLocalFile: "/data/holidays.json"
  key: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbnYiOiJkZXYiLCJpYXQiOjE2OTgyMDYzMTMsImV4cCI6MTcyOTc0MjMxMywiaXNzIjoiRGlmaXNvZnQiLCJzdWIiOiJtYXJrZXQtY29sbGVjdG9yLWxvdHRlIn0.DkpC0Jx2tGPpIkCGNSQNTYG2lRzBhixQu6yKCgDhh73q_yI05rAs8ISEHjBdvloUdOaaSBuuszikHaqHkDZrkr4fwLwkFLwE-X22JQXlo2pWap2Tid9ycV0zjwR8RV1k9_NpCzuyg_DvFEZhanwF34OEiu9WFGPTTwPwBk7lfOaMED7tSTrQ1rKFN3FIIAXjbljSH76FpISXeB76kH4HGp1pXFic1lvwVnTIvipXGIQViYsD0AzDjB8a55FRFyoU-eDOx4VfFZVmitKIKQlYy-8CM4puRSe4acL44teIECnlntq3qJaklGJ_o3ASwRv_lpbzSTOuVw0j38Tqs5k9ZQ"
