#!/usr/bin/env bash
export TRADEX_ENV_ENABLE_ENCRYPT_PASSWORD=true
export UV_THREADPOOL_SIZE=20
export TRADEX_ENV_NODE_ID=$(cat id)
export TRADEX_ENV_KAFKA_PASSWORD="aq1sw2de3fr4"
export CONTAINER_APP_ENV_DIR="/appEnv"
export TRADEX_ENV_TOTAL_NODE="1"
export TRADEX_ENV_DOMAINS="nhsv"
export TRADEX_ENV_ZK_SERVER_PORT_1="2888"
export TRADEX_ENV_ZK_SERVER_PORT_2="3888"
export TRADEX_ENV_ZOOKEEPER_PORT="2181"
export TRADEX_ENV_KAFKA_PORT="9092"
export TRADEX_ENV_KAFKA_EXTERNAL_PORT="19092"
export TRADEX_ENV_MYSQL_PORT="3306"
export TRADEX_ENV_MONGO_PORT="27017"
export TRADEX_ENV_WS_PORT="8001"
export TRADEX_ENV_REDIS_PORT="6379"
export SCC_STATE_SERVER_PORT="7777"
export SCC_BROKER_SERVER_PORT="8888"
export MINIO_PORT="9000"
# APP
export TRADEX_ENV_NODE1="172.33.30.38"
export TRADEX_ENV_NODE2="172.33.30.39"
export TRADEX_ENV_NODE3="172.33.30.40"
# DB
export TRADEX_ENV_NODE4="172.33.10.65"
export TRADEX_ENV_NODE5="172.33.10.66"
# KAFKA
export TRADEX_ENV_NODE6="172.33.10.67"
export TRADEX_ENV_NODE7="172.33.10.68"
export TRADEX_ENV_NODE8="172.33.10.69"
# MARKET
export TRADEX_ENV_NODE9="172.33.10.70"
export TRADEX_ENV_NODE10="172.33.10.71"


export TRADEX_ENV_NODE_ID=$(cat id)
nodeAddressVar="TRADEX_ENV_NODE$TRADEX_ENV_NODE_ID"
export localIp=${!nodeAddressVar}
export DOCKERMASTERIP="$localIp"

export TRADEX_ENV_DOMAIN="nhsv"
export TRADEX_ENV_ENV_NAME="nhsv"
export TRADEX_ENV_ENVIRONMENT="prod"

export BAMBOO_KAFKA_DIR="/home/kafka"
export BAMBOO_KEY_DIR="keys"
export BAMBOO_KEY_PASSWORD="aq1sw2de3fr4"

TRADEX_ENV_ZOOKEEPER_URLS=""
TRADEX_ENV_KAFKA_URLS=""
export TRADEX_ENV_ZOOKEEPER_URLS="$TRADEX_ENV_NODE6:$TRADEX_ENV_ZOOKEEPER_PORT"
export TRADEX_ENV_KAFKA_URLS="$TRADEX_ENV_NODE6:$TRADEX_ENV_KAFKA_PORT"
export TRADEX_ENV_KAFKA_PRIMARY_URL="$TRADEX_ENV_NODE6:$TRADEX_ENV_KAFKA_PORT"
export TRADEX_ENV_MYSQL_HOST="$TRADEX_ENV_NODE4"
export TRADEX_ENV_MYSQL_USER="admin"
export TRADEX_ENV_MYSQL_PASSWORD="lAhV1MWqLo2sreN9o7frducCc0o6ng9h"
export TRADEX_ENV_MYSQL_TRADEX_AAA_DB="tradex-aaa"
export TRADEX_ENV_MYSQL_TRADEX_AAA_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_AAA_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"
export TRADEX_ENV_MYSQL_TRADEX_CONFIGURATION_DB="tradex-configuration"
export TRADEX_ENV_MYSQL_TRADEX_CONFIGURATION_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_CONFIGURATION_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"
export TRADEX_ENV_MYSQL_TRADEX_JOB_DB="tradex-job"
export TRADEX_ENV_MYSQL_TRADEX_JOB_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_JOB_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"
export TRADEX_ENV_MYSQL_TRADEX_NOTIFICATION_DB="tradex-notification"
export TRADEX_ENV_MYSQL_TRADEX_NOTIFICATION_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_NOTIFICATION_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"
export TRADEX_ENV_MYSQL_TRADEX_USER_DB="tradex-user"
export TRADEX_ENV_MYSQL_TRADEX_USER_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_USER_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"
export TRADEX_ENV_MYSQL_TRADEX_AI_ADVISOR_USER="$TRADEX_ENV_MYSQL_USER"
export TRADEX_ENV_MYSQL_TRADEX_AI_ADVISOR_PASSWORD="$TRADEX_ENV_MYSQL_PASSWORD"

export TRADEX_ENV_MONGO_HOST="${TRADEX_ENV_NODE5}"
export TRADEX_ENV_MONGO_USER="admin"
export TRADEX_ENV_MONGO_PASSWORD="N4K0W71dUtq5zwFHvPZb8ck32pDOIegC"
export TRADEX_ENV_MONGO_TRADEX_MARKET_DB="tradex-market"
export TRADEX_ENV_MONGO_TRADEX_MARKET_USER="$TRADEX_ENV_MONGO_USER"
export TRADEX_ENV_MONGO_TRADEX_MARKET_PASSWORD="$TRADEX_ENV_MONGO_PASSWORD"
export TRADEX_ENV_REDIS_HOST=$TRADEX_ENV_NODE4
export TRADEX_ENV_BIOMETRIC_VALIDATE_PASSWORD=false
export TRADEX_ENV_ENABLE_BIOMETRIC=true

export liquibase_command_username=$TRADEX_ENV_MYSQL_USER
export liquibase_command_password=$TRADEX_ENV_MYSQL_PASSWORD

export MINIO_HOST="$TRADEX_ENV_NODE3"
export MINIO_ACCESS_KEY=riGsOl5pizzfssffdYwT 
export MINIO_SECRET_KEY=cuheNWhrOc2PYStg29gFDw015To5V01x9zy18e2b 

export TRADEX_ENV_NSHV_ADMIN_PORT=8082
export TRADEX_ENV_EKYC_ADMIN_PORT=8081
export TRADEX_ENV_MYSQL_TRADEX_EKYC_ADMIN_DB="ekyc_admin"



export TRADEX_ENV_JWT_PUBLIC_KEY=$(cat << EndOfMessage
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFmFhqTZrJuhs0LG86sywPoVLsM/
KvmP+FMaZKZsijbwDa0OHJjCE0GF7QtZK09SCQzyHfwX+W2vODvwstlqwgrPsFF3
OJ0G6Xb9iUI2LEtZhTcmoRLUnX6xY1kFuNPT/vMtiL3uXZXR/+gGgSXtfAccHIiM
WNAYRXsG+1V28vXDAgMBAAE=
-----END PUBLIC KEY-----
EndOfMessage
)

export TRADEX_ENV_JWT_PRIVATE_KEY=$(cat << EndOfMessage
-----BEGIN RSA PRIVATE KEY-----
MIICWgIBAAKBgFmFhqTZrJuhs0LG86sywPoVLsM/KvmP+FMaZKZsijbwDa0OHJjC
E0GF7QtZK09SCQzyHfwX+W2vODvwstlqwgrPsFF3OJ0G6Xb9iUI2LEtZhTcmoRLU
nX6xY1kFuNPT/vMtiL3uXZXR/+gGgSXtfAccHIiMWNAYRXsG+1V28vXDAgMBAAEC
gYA8iX0ZsVF2FQ0CFUPl+3ZgJz7uLaNEDEWi/PAfUrrMl9zHsAlKi8M1xfkceXo+
M32HUZtRRG0Z7Smb7xMiz3zTwgMb0FBHDSjcywB+3vrGKFMarKRhNkEqYXsnf4P0
5JCvWciDfjhQHIHIuWJBESWdH56HJP22azHxA0JvTTYi8QJBAJovxkPHeU08vF65
tyleHL6SZcECW6QJuS/5quO12LmjFkTnb4barkwkDgkeGwDTTuxMUUsdM1FdsvKe
o8M+Dv0CQQCUoo5wZ+mYMewaIVCqNCcT+BSOJC/MS9ELCIPSh/O3uQ92G3hw5LWE
cDq9Ajcp8W6By2TVaqLQWoMLUcMLfRO/AkAXeizLR0VOIHBiUA72qpDf57S8tdo0
WRKsnmyJ7beJVK7gYQkXVJbzmw3UD5R3BLXgvyIluNWGjyjfTo6K/RkVAkBzESWU
f92npX5S/FembJmULAo9wGYAkvFSyVTEN9vF7864cKvdOjIMRZYznPN31SDn+r4l
OlixVGD+8l09F6ehAkApzMHhvUyD7wR+WIuSofW83TgjnRo8tJc+JOTRQH/CQY+i
8ed+cAocdrFlsaCJBVu1p2tLjLnIUWMbZf6YkxMF
-----END RSA PRIVATE KEY-----
EndOfMessage
)

export TRADEX_ENV_PASSWORD_RSA_PUBLIC_KEY=$(cat << EndOfMessage
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDMPqmHVmGToCxKgal7uCELODNQ
OzIXVq/6TdWwOO2xziVLrNlbHyYVmRZ+TsEEtIQjzhkp94kxaBIq+mS11BcKD9FM
XGCAA3Dlvdu7koAxTKF09TSLzckpLkP1lAWJ05+9bwY1rpPS5z0Uubz9iP8vTLwz
AkOK1gAcoIC2ZPVyOQIDAQAB
-----END PUBLIC KEY-----
EndOfMessage
)

export TRADEX_ENV_PASSWORD_RSA_PRIVATE_KEY=$(cat << EndOfMessage
-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQDMPqmHVmGToCxKgal7uCELODNQOzIXVq/6TdWwOO2xziVLrNlb
HyYVmRZ+TsEEtIQjzhkp94kxaBIq+mS11BcKD9FMXGCAA3Dlvdu7koAxTKF09TSL
zckpLkP1lAWJ05+9bwY1rpPS5z0Uubz9iP8vTLwzAkOK1gAcoIC2ZPVyOQIDAQAB
AoGBAJjOqPdgYVCZnYmAyNSPRemm+n0kTK25ZZ/Xa/CUJwHIQY8EmvnZrByslG+b
bD2g8Nv47kq/sB0Ox8jv3TlMnI7MChCSIaxK3lSXTw7S5D5ykmPdlgoKMHm1ZsuV
VD4aG+5qacuwUawh7fciK43KY8/Ay4l0s+klJiJ+JF/rUNGhAkEA7+K9az1ubeK0
WgvS97Rlmi5+xrv4nXENEaz/jcJo83MY4oe7cO5qnphxdEvGrM7pb13akzyKI3i/
sqURHENR3wJBANn3A2mraOYSWgsI5AqtobnLxRp+4kwmIlimfmtX3pjyv6pQ1ZPp
gj67pZFdFP8ZSfnLucuPAz1fGZNknXmPrucCQBYLyYq8h5STvC12XrojGx9TXJVZ
Gx0lEaVpN8dIcarGDihrfv9++c9/hRXCDQ0+qtdwUbEsZCmkZEG/x9XIHhMCQAmr
6D7cGD99OPmcX2IJ6k8wN4LBdpEicAu2940TzRDEVLTd+Vwi1GCsOuCEXNYk7R9k
Zs4dfmtOuPfNUx99vKkCQCcltrI+WghJdUPTb0yOMQXJ+w08UDS3sqtKfVvXtCMY
QhXMj/uEhCN8VVPJUY7ObrqpQwQKGOvc2YmuvMKhh7Q=
-----END RSA PRIVATE KEY-----
EndOfMessage
)

export TRADEX_ENV_INIT_MARKET_BY_REALTIME=true
export TRADEX_ENV_LOTTE_API=http://172.33.30.36:8100
export TRADEX_ENV_LOTTE_API_KEY=qJxAtDmMuDEan9kUWsY4UuMugFvrYeMe
export TRADEX_ENV_LOTTE_WS=ws://172.33.30.36:9900
export TRADEX_ENV_HOLIDAY_URL=http://$TRADEX_ENV_NODE1:9000/mts/holidays.json