INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(290, 'MARKET_V2_QUERY_SYMBOL_STATIC_INFO', 'get:/api/v2/market/symbol/staticInfo', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/staticInfo","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(291, 'MARKET_V2_QUERY_SYMBOL_LATEST_INFO', 'get:/api/v2/market/symbol/latest', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/latest","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(292, 'MARKET_V2_QUERY_SYMBOL_QUOTE', 'get:/api/v2/market/symbol/{symbol}/quote', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbol}/quote","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(293, 'MARKET_V2_QUERY_SYMBOL_PERIOD', 'get:/api/v2/market/symbol/{symbol}/period/{periodType}', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbol}/period/{periodType}","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(294, 'MARKET_V2_QUERY_SYMBOL_QUOTE_TICKS', 'get:/api/v2/market/symbol/{symbol}/ticks', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbol}/ticks","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(295, 'MARKET_V2_QUERY_SYMBOL_QUOTE_MINUTES', 'get:/api/v2/market/symbol/{symbolCode}/minutes', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbolCode}/minutes","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(296, 'MARKET_V2_QUERY_SESSION_STATUS', 'get:/api/v2/market/sessionStatus', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/sessionStatus","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(297, 'MARKET_V2_QUERY_FOREIGNER_DATA', 'get:/api/v2/market/symbol/{symbolCode}/foreigner', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbolCode}/foreigner","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(298, 'MARKET_V2_QUERY_ETF_NAV_DAILY', 'get:/api/v2/market/etf/{symbolCode}/nav/daily', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/etf/{symbolCode}/nav/daily","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(299, 'MARKET_V2_QUERY_ETF_INDEX_DAILY', 'get:/api/v2/market/etf/{symbolCode}/index/daily', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/etf/{symbolCode}/index/daily","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(300, 'MARKET_V2_QUERY_PUTTHROUGH_ADVERTISE', 'get:/api/v2/market/putthrough/advertise', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/putthrough/advertise","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(301, 'MARKET_V2_QUERY_PUTTHROUGH_DEAL', 'get:/api/v2/market/putthrough/deal', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/putthrough/deal","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(302, 'MARKET_V2_QUERY_RANKING_UP_DOWN', 'get:/api/v2/market/ranking/{symbolType}/upDown', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/ranking/{symbolType}/upDown","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(303, 'MARKET_V2_QUERY_RANKING_TRADE', 'get:/api/v2/market/ranking/{symbolType}/trade', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/ranking/{symbolType}/trade","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(313, 'MARKET_V2_QUERY_FOREIGNER_SUMMARY', 'get:/api/v2/market/symbol/foreignerSummary', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/foreignerSummary","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(681, 'MARKET_V2_QUERY_CURRENT_DIVIDEND', 'get:/api/v2/market/currentDividendEvent', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/currentDividendEvent","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(682, 'MARKET_V2_QUERY_MINUTE_CHART', 'get:/api/v2/market/symbol/{symbol}/minuteChart', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/{symbol}/minuteChart","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(683, 'MARKET_V2_QUERY_PRICE_BOARD', 'get:/api/v2/market/priceBoard', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/priceBoard","forwardType":"SERVICE"}');
INSERT INTO t_scope(id, name, uri_pattern, forward_type, forward_data)VALUES(684, 'MARKET_V2_QUERY_ODDLOT_BIDASK', 'get:/api/v2/market/symbol/oddlotLatest', 'CONNECTION', '{"service":"market-v2","uri":"/api/v2/market/symbol/oddlotLatest","forwardType":"SERVICE"}');

INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(684, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(290, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(291, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(292, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(293, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(294, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(295, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(296, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(297, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(298, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(299, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(300, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(301, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(302, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(313, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(681, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(682, 4);
INSERT INTO t_scope_scope_group_map (scope_id,scope_group_id)VALUES(683, 4);
