//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.11 at 01:20:18 PM ICT 
//


package com.techx.tradex.notification.model.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.techx.tradex.notification.model.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.techx.tradex.notification.model.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMT }
     * 
     */
    public SendMT createSendMT() {
        return new SendMT();
    }

    /**
     * Create an instance of {@link SendMTResponse }
     * 
     */
    public SendMTResponse createSendMTResponse() {
        return new SendMTResponse();
    }

}
