//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.11 at 01:20:18 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://1sms.vn/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.techx.tradex.notification.model.wsdl;
