package com.difisoft.nhsv.admin.domain.vn._1sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2024-08-13T16:05:14.651+07:00
 * Generated source version: 3.4.5
 */
@WebService(targetNamespace = "http://1sms.vn/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebMethod(operationName = "SendMT", action = "http://1sms.vn/SendMT")
    @RequestWrapper(localName = "SendMT", targetNamespace = "http://1sms.vn/", className = "vn._1sms.SendMT")
    @ResponseWrapper(localName = "SendMTResponse", targetNamespace = "http://1sms.vn/", className = "vn._1sms.SendMTResponse")
    @WebResult(name = "SendMTResult", targetNamespace = "http://1sms.vn/")
    public String sendMT(

        @WebParam(name = "user", targetNamespace = "http://1sms.vn/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://1sms.vn/")
        String pass,
        @WebParam(name = "sms", targetNamespace = "http://1sms.vn/")
        String sms,
        @WebParam(name = "senderName", targetNamespace = "http://1sms.vn/")
        String senderName,
        @WebParam(name = "phone", targetNamespace = "http://1sms.vn/")
        String phone,
        @WebParam(name = "isFlash", targetNamespace = "http://1sms.vn/")
        boolean isFlash,
        @WebParam(name = "isUnicode", targetNamespace = "http://1sms.vn/")
        boolean isUnicode
    );
}
