FROM node:16-alpine3.11 AS production

# Install dependencies for native modules
RUN apk add --no-cache \
    bash \
    git \
    python3 \
    make \
    g++ \
    && rm -rf /var/cache/apk/*

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install --frozen-lockfile --production=true

WORKDIR /app

# Copy built application from builder stage
COPY . /app/

COPY entrypoint.sh ./entrypoint.sh


ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh", "node index.js"]
