spring:
  application:
    name: order
  devtools:
    restart:
      exclude: resources/db/**
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tradex-order?useSSL=false
    username: root
    password: admin1234
  redis:
    host: localhost
    port: 6379

logging:
  file:
    name: /logs/application.log
  level:
    root: WARN
    org.springframework: WARN
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #    org.springframework.transaction: DEBUG
    #    org.springframework.orm.jpa: DEBUG
    com.techx: INFO
    in: INFO
    out: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5p %C %M %L - %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %C{1} %M %L - %m%n"

app:
  domain: mas
  kafkaUrl: localhost:9092
  enablePlaceOrderAfterMarketClose: true
