export class Constants {
  static ACCOUNT_NUMBER_IS_EMPTY = 'ACCOUNT_NUMBER_IS_EMPTY';
  static TOKEN_REQUEST_MFA_DATA_FIELD_IS_EMPTY = 'TOKEN_REQUEST_MFA_DATA_FIELD_IS_EMPTY';
  static NHSV_OTP = 'NHSV_OTP';
}
