export const WRONG_OTP = 'WRONG_OTP';
export const WRONG_MOBILE_OTP = 'WRONG_MOBILE_OTP';
export const VERIFY_TYPE_NOT_FOUND = 'VERIFY_TYPE_NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

// OTP Strategy errors
export const OTP_EXPIRED = 'OTP_EXPIRED';
export const OTP_LOCKED = 'OTP_LOCKED';
export const OTP_MAX_RESEND = 'OTP_MAX_RESEND';
export const OTP_INCORRECT = 'OTP_INCORRECT';
export const OTP_INCORRECT_MAX = 'OTP_INCORRECT_MAX';
export const OTP_TX_TYPE_NOT_FOUND = 'OTP_TX_TYPE_NOT_FOUND';
export const OTP_GENERATE_TOO_FAST = 'OTP_GENERATE_TOO_FAST';
export const PHONE_NUMBER_NOT_FOUND = 'PHONE_NUMBER_NOT_FOUND';