export const WRONG_OTP = 'WRONG_OTP';
export const WRONG_MOBILE_OTP = 'WRONG_MOBILE_OTP';
export const VERIFY_TYPE_NOT_FOUND = 'VERIFY_TYPE_NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';