export const FAQ_ALREADY_REVIEWED = "FAQ_ALREADY_REVIEWED";

// store services
export const AWS_GET_SIGNED_DATA_FAILED = "AWS_GET_SIGNED_DATA_FAILED";
export const STORAGE_SERVICE_ACTION_NOT_SUPPORTED =
  "STORAGE_SERVICE_ACTION_NOT_SUPPORTED";

export const DATA_VIEW_CODE_NOT_EXISTED = "DATA_VIEW_CODE_NOT_EXISTED";
export const KEY_ALREADY_EXISTED = "KEY_ALREADY_EXISTED";
export const UPLOAD_LANGUAGE_RESOURCE_FAILED =
  "UPLOAD_LANGUAGE_RESOURCE_FAILED";
export const INVALID_PARAMETER = "INVALID_PARAMETER";
export const REQUIRE_AUTHENTICATE = "REQUIRE_AUTHENTICATE";
