export const BIOMETRIC_KEYS = {
  NOT_FOUND: "LOGIN_BIOMETRIC_NOT_FOUND",
  VERIFY_FAILED: "LOGIN_BIOMETRIC_SIGNATURE_VERIFICATION_FAILED",
  PASSWORD_NOT_MATCH: "LOGIN_BIOMETRIC_PASSWORD_NOT_MATCH",
  PUBLIC_KEY_EXISTED: "LOGIN_BIOMETRIC_PUBLIC_KEY_EXISTED",
  OTP_NOT_VERIFIED: "LOGIN_BIOMETRIC_OTP_DOES_NOT_VERIFIED",
  OTP_VERIFY_FAILED: "LOGIN_BIOMETRIC_OTP_VERIFIED_FAILED",
  VERIFY_BIOMETRIC_FAILED: "VERIFY_BIOMETRIC_FAILED",
  BIOMETRIC_UNREGISTER_SUCCESS: "BIOMETRIC_UNREGISTER_SUCCESS",
  BIOMETRIC_ACTIVE_ON_ANOTHER_DEVICE: "BIOMETRIC_ACTIVE_ON_ANOTHER_DEVICE"
};

export const BIOMETRIC_STATUS = {
  INACTIVE: "INACTIVE",
  ACTIVE: "ACTIVE"
};

export const BIOMETRIC_CANCEL_REASON = {
  CHANGE_DEVICE: "hủy do user đổi device",
  CHANGE_PASS: "hủy do user đổi password",
  CANCEL: "hủy do user",
  OTP_VERIFY: "huỷ do user không xác thực OTP"
};

export const BIOMETRIC_LOGIN_ERROR = {
  kbsv: "INVALID_CLIENT_CREDENTIAL",
  vcsc: "LOGIN_WRONG_PASSWORD",
  kbfinance: "INVALID_CLIENT_CREDENTIAL",
  kis: "LOGIN_WRONG_PASSWORD"
};