export enum GrantType {
  PASSWORD = "password",
  DEMO = "demo",
  PASSWORD_TRADEX = "password_tradex",
  PASSWORD_OTP = "password_otp",
  PASSWORD_FACEID = "password_faceid",
  PASSWORD_CA = "password_ca",
  ACCESS_GOOGLE = "access_google",
  ACCESS_FACEBOOK = "access_facebook",
  CLIENT_CREDENTIALS = "client_credentials",
  ACCESS_DOMAIN = "access_domain",
  LOGIN_BIOMETRIC = "biometric",
  ACCESS_APPLE = "access_apple",
  SOCIAL_LOGIN = "social_login",
  LINK_ACCOUNT = "link_account",
  KB_FINA = "kbfina",
  ORGANIZATION_LOGIN = "organization_login",
  ORGANIZATION_SOCIAL_LOGIN = "organization_social_login",
  BIOMETRIC_OTP = "biometric_otp",
}
