class FieldModel<T> {
  public id: boolean = false;
  public autoGenerated: boolean = false;

  constructor(private fieldName: string, private rowData: () => any, private defaultValue?: T) {
  }

  public get(): T { // tslint:disable-line
    const row = this.rowData();
    return row ? row[this.fieldName] : null;
  }

  public getDefault(defaultValue: T = null): T { // tslint:disable-line
    const data: T = this.get();
    return (data) ? data : defaultValue;
  }

  public autoGeneratedField() {
    this.autoGenerated = true;
  }

  public idField(): FieldModel<T> {
    this.id = true;
    return this;
  }

  public initDefault(): void {
    if (this.defaultValue !== undefined && this.defaultValue !== null) {
      const row = this.rowData();
      if (row[this.fieldName] === undefined || row[this.fieldName] === null) {
        row[this.fieldName] = this.defaultValue;
      }
    }
  }

  public set(value: T): void { // tslint:disable-line
    const row = this.rowData();
    if (row) {
      row[this.fieldName] = value;
    }
  }

  public getFieldName(alias?: string) {
    return alias ? `${alias}.${this.fieldName}` : this.fieldName;
  }

  public clone(): FieldModel<T> {
    return new FieldModel(this.fieldName, this.rowData);
  }
}

export default FieldModel;
