package com.techx.tradex.common.constants;

public enum ErrorCodeEnums {
    INTERNAL_SERVER_ERROR,
    INVALID_PARAMETER,
    TARGET_NOT_FOUND,
    URI_NOT_FOUND,
    INVALID_ACCOUNT,
    LOGIN_FAILED,
    INVALID_URI,
    HTS_ERROR,
    INVALID_FORMAT,
    INVALID_VALUE,
    VALUE_MUST_GREATER_OR_EQUAL,
    VALUE_MUST_GREATER,
    VALUE_MUST_LESS_OR_EQUAL,
    VALUE_MUST_LESS,
    VALUE_MUST_EQUAL,
    VALUE_MUST_IN,
    TOKEN_EXPIRED,
    EMPTY_VALUE,
    INDEX_NOT_FOUND,
    STOCK_NOT_FOUND;
}
