package com.techx.tradex.order.constants;

public interface Constants {
    String INVALID_PARAMETER = "INVALID_PARAMETER";
    String ERROR_TRAILING_ORDER_NOT_FOUND = "TRAILING_ORDER_NOT_FOUND";
    String ERROR_TRAILING_ORDER_INVALID_STATUS = "TRAILING_ORDER_INVALID_STATUS";
    String ERROR_PRICE_CANNOT_GT_CEILING = "PRICE_CANNOT_GT_CEILING";
    String ERROR_PRICE_CANNOT_LT_FLOOR = "PRICE_CANNOT_LT_FLOOR";
    String ERROR_INVALID_SYMBOL_CODE = "INVALID_SYMBOL_CODE";
    String ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

    String FROM_DATE_INVALID = "FROM_DATE_INVALID";
    String FROM_DATE_TIME_INVALID = "FROM_DATE_TIME_INVALID";
    String STOP_PRICE_OR_STOP_VOLUME_MUST_BE_SET = "STOP_PRICE_OR_STOP_VOLUME_MUST_BE_SET";
    String STOP_PRICE_MUST_BE_SET = "STOP_PRICE_MUST_BE_SET";
    String ACCOUNT_NUMBER_MUST_BE_REQUIRED = "ACCOUNT_NUMBER_MUST_BE_REQUIRED";
    String UNABLE_TO_STOP_ORDERS_OF_ANOTHER_ACCOUNT = "UNABLE_TO_STOP_ORDERS_OF_ANOTHER_ACCOUNT";
    String TO_DATE_INVALID = "TO_DATE_INVALID";
    String TO_DATE_MUST_BE_GTE_THAN_FROM_DATE = "TO_DATE_MUST_BE_GTE_THAN_FROM_DATE";
    String SELL_STOP_PRICE_CANNOT_GTE_THAN_CURRENT_PRICE = "SELL_STOP_PRICE_CANNOT_GTE_THAN_CURRENT_PRICE";
    String BUY_STOP_ORDER_PRICE_CANNOT_LTE_THAN_CURRENT_PRICE = "BUY_STOP_ORDER_PRICE_CANNOT_LTE_THAN_CURRENT_PRICE";
    String ALREADY_EXISTED_ERROR = "ALREADY_EXISTED_ERROR";
    String OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND";
    String STOP_ORDER_INVALID_STATUS = "STOP_ORDER_INVALID_STATUS";
    String OCO_ORDER_INVALID_STATUS = "OCO_ORDER_INVALID_STATUS";
    String BULLBEAR_ORDER_INVALID_STATUS = "BULLBEAR_ORDER_INVALID_STATUS";
    String PL_ORDER_INVALID_STATUS = "PL_ORDER_INVALID_STATUS";
    String VALIDATE_ORDER_FAILED = "VALIDATE_ORDER_FAILED";

    int DEFAULT_FETCH_COUNT = 20;
    String DEFAULT_STOP_ORDER_HISTORY_FROM_DATE = "19700101";
    String DEFAULT_HISTORY_FROM_DATE = "19700101";
    String CUT_LOSS_ORDER_IS_GENERATED = "CUT_LOSS_ORDER_HAS_BEEN_GENERATED";
    int MAX_FETCH_COUNT = 100;
    int MARKET_TIMEZONE = 7;
    String KBSV_DOMAIN = "kbsv";


    String REDIS_KEY_SYMBOL_INFO = "realtime_mapSymbolInfo";
    String REDIS_KEY_SYMBOL_DAILY = "realtime_mapSymbolDaily";
    String REDIS_KEY_FOREIGNER_DAILY = "realtime_mapForeignerDaily";
    String REDIS_KEY_SYMBOL_QUOTE = "realtime_listQuote";
    String REDIS_KEY_SYMBOL_BID_OFFER = "realtime_listBidOffer";
    String REDIS_KEY_SYMBOL_BID_OFFER_ODD_LOT = "realtime_listBidOfferOddLot";
    String REDIS_KEY_SYMBOL_QUOTE_MINUTE = "realtime_listQuoteMinute";
    String REDIS_KEY_DEAL_NOTICE = "realtime_listDealNotice";
    String REDIS_KEY_ADVERTISED = "realtime_listAdvertised";
    String REDIS_KEY_MARKET_STATUS = "realtime_mapMarketStatus";

    String MAS_DOMAIN = "mas";
    String FIELD_IS_REQUIRED = "FIELD_IS_REQUIRED";
    String NULL = "null";
}
